TYPE=VIEW
query=select `payrollmanagement`.`employeedetails`.`ID` AS `id`,`payrollmanagement`.`employeedetails`.`NAME` AS `name`,`payrollmanagement`.`employeedetails`.`DOB` AS `dob`,`payrollmanagement`.`employeedetails`.`ADDRESS` AS `address`,`payrollmanagement`.`employeedetails`.`PINCODE` AS `pincode`,`payrollmanagement`.`employeedetails`.`EMAIL` AS `email`,`payrollmanagement`.`employeedetails`.`PHNO` AS `phno` from `payrollmanagement`.`employeedetails`
md5=3c308d11b3ed7a468cd8ef2538e16b74
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=0001677132516371328
create-version=2
source=select id,name,dob,address,pincode,email,phno from employeedetails
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `payrollmanagement`.`employeedetails`.`ID` AS `id`,`payrollmanagement`.`employeedetails`.`NAME` AS `name`,`payrollmanagement`.`employeedetails`.`DOB` AS `dob`,`payrollmanagement`.`employeedetails`.`ADDRESS` AS `address`,`payrollmanagement`.`employeedetails`.`PINCODE` AS `pincode`,`payrollmanagement`.`employeedetails`.`EMAIL` AS `email`,`payrollmanagement`.`employeedetails`.`PHNO` AS `phno` from `payrollmanagement`.`employeedetails`
mariadb-version=100427
